stages:
  - deploy_dev
  - deploy_prod


deploy_to_dev:
  stage: deploy_dev
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
  before_script:

    - apk add --no-cache openssh-client rsync
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H  $SSH_PORT_SUP $SUP_SERVER >> ~/.ssh/known_hosts
  script:
    - chmod 600 $SSH_PRIVKEY_SUP
    - ssh -vvv $SSH_PORT_SUP -i $SSH_PRIVKEY_SUP -o StrictHostKeyChecking=no $SSH_LOGIN@$SUP_SERVER "echo Connection OK"
    # Синхронизируем файлы из репозитория в папку на сервере
    - rsync -avz -e "ssh -p 25523 -i $SSH_PRIVKEY_SUP" --delete ./ $SSH_LOGIN@$SUP_SERVER:/var/prod/html/mysite.ru/
    # Если требуется перезапустить веб-сервер:
    # - ssh $SERVER_USER@$SERVER_HOST "systemctl restart nginx"

deploy_to_prod:
  stage: deploy_prod
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  before_script:
    - apk add --no-cache openssh-client rsync
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H  $SSH_PORT_CHEF $CHEF_SERVER >> ~/.ssh/known_hosts
  script:
    - chmod 600 $SSH_PRIVKEY_CHEF
    - ssh -vvv $SSH_PORT_CHEF -i $SSH_PRIVKEY_CHEF -o StrictHostKeyChecking=no $SSH_LOGIN@$CHEF_SERVER "echo Connection OK"
    # Синхронизируем файлы из репозитория в папку на сервере
    - rsync -avz -e "ssh $SSH_PORT_CHEF -i $SSH_PRIVKEY_CHEF" --delete ./ $SSH_LOGIN@$CHEF_SERVER:/var/prod/html/mysite.ru/
    # Если требуется перезапустить веб-сервер:
    # - ssh $SERVER_USER@$SERVER_HOST "systemctl restart nginx"

