stages:
  - deploy


deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - apk add --no-cache openssh-client rsync
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H  -p 25523 $SUP_SERVER >> ~/.ssh/known_hosts
    - echo "$SSH_PRIVKEY_SUP" > /tmp/deploy_key
    - chmod 600 /tmp/deploy_key
  script:
    - chmod 600 $SSH_PRIVKEY_SUP
    # Синхронизируем файлы из репозитория в папку на сервере
    - rsync -avz -e "ssh -p 25523 -i $SSH_PRIVKEY_SUP" --delete ./ $SSH_LOGIN_SUP@$SUP_SERVER:/var/www/html/mysite.ru/
    # Если требуется перезапустить веб-сервер:
    # - ssh $SERVER_USER@$SERVER_HOST "systemctl restart nginx"
  only:
    - main
