stages:
  - deploy


deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - apk add --no-cache openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVKEY_SUP" | tr -d '\r' | ssh-add -
    - ping $SUP_SERVER -c 5
    - ssh-keyscan -p 25523 -H $SUP_SERVER >> ~/.ssh/known_hosts
  script:
    # Синхронизируем файлы из репозитория в папку на сервере
    - rsync -avz -e "ssh -p 25523" --delete ./ $SSH_LOGIN_SUP@$SUP_SERVER:/var/www/html/mysite.com/
    # Если требуется перезапустить веб-сервер:
    # - ssh $SERVER_USER@$SERVER_HOST "systemctl restart nginx"
  only:
    - main
